import type { Metadata } from "next";
import { Karla, Rubik } from "next/font/google";
import "./globals.css";
import { NavbarDesktop } from "@/components/NavbarDesktop";
import { NavbarTouch } from "@/components/NavbarTouch";

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${karla.variable} ${rubik.variable} antialiased`}
      >
        <NavbarDesktop />
        <NavbarTouch />
        {children}
      </body>
    </html>
  );
}
