import type { Metadata } from "next";
import { Karla, Rubik } from "next/font/google";
import "./globals.css";
import { NavbarDesktop } from "@/components/layout/NavbarDesktop";
import { NavbarTouch } from "@/components/layout/NavbarTouch";
import { ComplianceStrip } from "@/components/sections/compliance-strip";
import { Footer } from "@/components/layout/footer";
import { ToasterProvider } from "@/components/ui/toaster";

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (process.env.NODE_ENV !== "production") {
  // Load Storyblok only in preview mode
  const { initStoryblok } = require("@/lib/storyblok");
  initStoryblok();
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${karla.variable} ${rubik.variable} antialiased`}>
        <ToasterProvider />
        <NavbarDesktop />
        <NavbarTouch />
        {children}
        <ComplianceStrip />
        <Footer />
      </body>
    </html>
  );
}
